/**
 * Re-export surface for the generated backend bindings.
 *
 * `backend.ts` / `backend.d.ts` are generated by `pnpm bindgen` and must never
 * be edited. Application code imports the actor factory and the domain types
 * from here so there is a single, greppable integration point.
 *
 * The enums (`Capability`, `EventKind`, `LotStatus`, `LotType`, `RefKind`,
 * `Role`, `Site`, `UserRole`) are runtime values, so they are re-exported as
 * values — never with `export type`, which would break `LotStatus.open`,
 * `Capability.freeze_lot` and `switch` statements.
 */
export { createActor } from "@/backend";
export {
  Capability,
  EventKind,
  LotStatus,
  LotType,
  RefKind,
  Role,
  Site,
  UserRole,
} from "@/backend";
export type {
  ActorRole,
  ActivityPoint,
  AnalysisDocumentView,
  AnalyticsBucket,
  AnalyticsPoint,
  CapabilityRow,
  CountBucket,
  EnquiryError,
  EnquiryView,
  EventView,
  FileHash,
  FileId,
  HashChainEntry,
  HashHex,
  LotId,
  LotSearchHit,
  LotView,
  MergeInput,
  NewAnalysisDocumentInput,
  NewEnquiryInput,
  NewEventInput,
  NewLotInput,
  NewRefEntryInput,
  PermissionsError,
  PermissionsView,
  PrincipalOverride,
  PurgeError,
  PurgeOutcome,
  PurgeRequestView,
  PurgeResult,
  RefEntryView,
  ReferenceError,
  RegisterAnalytics,
  RegisterError,
  RegisterSummary,
  RoleInfo,
  RolePermissions,
  SetPrincipalOverrideInput,
  SplitInput,
  StatusChange,
  StatusChangeInput,
  Timestamp,
  UpdateRefEntryInput,
  UpdateRolePermissionsInput,
} from "@/backend";
