/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result_18 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const HashHex = IDL.Text;
export const FileId = IDL.Text;
export const NewAnalysisDocumentInput = IDL.Record({
  'title' : IDL.Text,
  'contentHash' : HashHex,
  'note' : IDL.Text,
  'fileId' : FileId,
  'docKind' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const AnalysisDocumentView = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'contentHash' : HashHex,
  'note' : IDL.Text,
  'fileId' : FileId,
  'docKind' : IDL.Text,
  'uploadedAt' : Timestamp,
  'uploadedBy' : IDL.Principal,
});
export const ReferenceError = IDL.Variant({
  'notAuthorized' : IDL.Null,
  'invalidInput' : IDL.Text,
  'duplicateEntry' : IDL.Text,
  'unknownDocument' : IDL.Text,
  'notAuthenticated' : IDL.Null,
  'unknownEntry' : IDL.Text,
});
export const Result_17 = IDL.Variant({
  'ok' : AnalysisDocumentView,
  'err' : ReferenceError,
});
export const RefKind = IDL.Variant({
  'status' : IDL.Null,
  'site' : IDL.Null,
  'form_default' : IDL.Null,
  'lot_kind' : IDL.Null,
  'caption' : IDL.Null,
  'event_kind' : IDL.Null,
});
export const NewRefEntryInput = IDL.Record({
  'key' : IDL.Text,
  'displayName' : IDL.Text,
  'value' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'kind' : RefKind,
});
export const RefEntryView = IDL.Record({
  'id' : IDL.Text,
  'key' : IDL.Text,
  'active' : IDL.Bool,
  'displayName' : IDL.Text,
  'value' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'kind' : RefKind,
});
export const Result_1 = IDL.Variant({
  'ok' : RefEntryView,
  'err' : ReferenceError,
});
export const LotId = IDL.Text;
export const EventKind = IDL.Variant({
  'cut' : IDL.Null,
  'merge' : IDL.Null,
  'retail' : IDL.Null,
  'moved' : IDL.Null,
  'assay' : IDL.Null,
  'note' : IDL.Null,
  'status_change' : IDL.Null,
  'sealed' : IDL.Null,
  'weighed' : IDL.Null,
  'correction' : IDL.Null,
  'split' : IDL.Null,
  'extracted' : IDL.Null,
  'photo' : IDL.Null,
});
export const FileHash = IDL.Record({
  'contentHash' : HashHex,
  'fileId' : FileId,
});
export const NewEventInput = IDL.Record({
  'kind' : EventKind,
  'fileHashes' : IDL.Vec(FileHash),
  'payload' : IDL.Text,
  'fileIds' : IDL.Vec(FileId),
});
export const LotStatus = IDL.Variant({
  'closed' : IDL.Null,
  'assayed' : IDL.Null,
  'open' : IDL.Null,
  'in_transit' : IDL.Null,
  'retailed' : IDL.Null,
  'frozen' : IDL.Null,
});
export const StatusChange = IDL.Record({
  'at' : Timestamp,
  'by' : IDL.Principal,
  'to' : LotStatus,
  'seq' : IDL.Nat,
  'from' : LotStatus,
});
export const HashChainEntry = IDL.Record({
  'at' : Timestamp,
  'contentHash' : HashHex,
  'eventSeq' : IDL.Nat,
});
export const EventView = IDL.Record({
  'at' : Timestamp,
  'by' : IDL.Principal,
  'seq' : IDL.Nat,
  'supersededBy' : IDL.Opt(IDL.Nat),
  'kind' : EventKind,
  'payloadHash' : HashHex,
  'payload' : IDL.Text,
  'fileIds' : IDL.Vec(FileId),
});
export const LotType = IDL.Variant({ 'gold' : IDL.Null, 'emerald' : IDL.Null });
export const LotView = IDL.Record({
  'id' : LotId,
  'gps' : IDL.Text,
  'status' : LotStatus,
  'grossG' : IDL.Text,
  'contentHash' : HashHex,
  'workingRef' : IDL.Text,
  'statusHistory' : IDL.Vec(StatusChange),
  'sealNo' : IDL.Text,
  'hashChain' : IDL.Vec(HashChainEntry),
  'parentIds' : IDL.Vec(LotId),
  'events' : IDL.Vec(EventView),
  'fileHashes' : IDL.Vec(FileHash),
  'photoFileIds' : IDL.Vec(FileId),
  'frozen' : IDL.Bool,
  'licence' : IDL.Text,
  'lotType' : LotType,
  'project' : IDL.Text,
  'openedAt' : Timestamp,
  'openedBy' : IDL.Principal,
  'fileIds' : IDL.Vec(FileId),
});
export const RegisterError = IDL.Variant({
  'duplicateLot' : LotId,
  'notAuthorized' : IDL.Null,
  'invalidInput' : IDL.Text,
  'unknownLot' : LotId,
  'lotFrozen' : LotId,
  'notAuthenticated' : IDL.Null,
});
export const Result_7 = IDL.Variant({ 'ok' : LotView, 'err' : RegisterError });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Role = IDL.Variant({
  'workshop' : IDL.Null,
  'admin' : IDL.Null,
  'field_officer' : IDL.Null,
  'assayer' : IDL.Null,
  'guest' : IDL.Null,
});
export const ActorRole = IDL.Record({
  'principal' : IDL.Principal,
  'role' : Role,
});
export const Result_16 = IDL.Variant({
  'ok' : ActorRole,
  'err' : RegisterError,
});
export const StatusChangeInput = IDL.Record({
  'to' : LotStatus,
  'payload' : IDL.Text,
});
export const Result_15 = IDL.Variant({ 'ok' : Role, 'err' : RegisterError });
export const PurgeRequestView = IDL.Record({
  'id' : IDL.Text,
  'confirmedBy' : IDL.Vec(IDL.Principal),
  'totalAdmins' : IDL.Nat,
  'confirmedCount' : IDL.Nat,
  'requiredConfirmations' : IDL.Nat,
  'requestedAt' : Timestamp,
  'requestedBy' : IDL.Principal,
});
export const PurgeResult = IDL.Record({
  'purgedAt' : Timestamp,
  'purgedBy' : IDL.Principal,
  'eventsRemoved' : IDL.Nat,
  'lotsRemoved' : IDL.Nat,
  'filesRemoved' : IDL.Nat,
});
export const PurgeOutcome = IDL.Variant({
  'pending' : PurgeRequestView,
  'executed' : PurgeResult,
});
export const PurgeError = IDL.Variant({
  'alreadyConfirmed' : IDL.Null,
  'notAuthorized' : IDL.Null,
  'invalidInput' : IDL.Text,
  'alreadyRequested' : IDL.Null,
  'notAuthenticated' : IDL.Null,
  'noPendingRequest' : IDL.Null,
  'invalidPhrase' : IDL.Null,
});
export const Result_4 = IDL.Variant({
  'ok' : PurgeOutcome,
  'err' : PurgeError,
});
export const Result_14 = IDL.Variant({ 'ok' : LotId, 'err' : RegisterError });
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result__1 = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const Capability = IDL.Variant({
  'change_status' : IDL.Null,
  'purge_register' : IDL.Null,
  'split_lot' : IDL.Null,
  'create_lot' : IDL.Null,
  'merge_lot' : IDL.Null,
  'manage_analysis_documents' : IDL.Null,
  'delete_lot' : IDL.Null,
  'freeze_lot' : IDL.Null,
  'manage_roles' : IDL.Null,
  'manage_reference_data' : IDL.Null,
  'append_event' : IDL.Null,
  'view_analytics' : IDL.Null,
});
export const RolePermissions = IDL.Record({
  'capabilities' : IDL.Vec(Capability),
  'role' : Role,
});
export const CapabilityRow = IDL.Record({
  'displayName' : IDL.Text,
  'roles' : IDL.Vec(Role),
  'capability' : Capability,
});
export const PrincipalOverride = IDL.Record({
  'principal' : IDL.Principal,
  'capabilities' : IDL.Vec(Capability),
  'role' : Role,
});
export const PermissionsView = IDL.Record({
  'roleDefaults' : IDL.Vec(RolePermissions),
  'capabilities' : IDL.Vec(CapabilityRow),
  'overrides' : IDL.Vec(PrincipalOverride),
});
export const PermissionsError = IDL.Variant({
  'unknownPrincipal' : IDL.Principal,
  'notAuthorized' : IDL.Null,
  'invalidInput' : IDL.Text,
  'notAuthenticated' : IDL.Null,
});
export const Result_13 = IDL.Variant({
  'ok' : PermissionsView,
  'err' : PermissionsError,
});
export const Result_12 = IDL.Variant({
  'ok' : IDL.Opt(PurgeRequestView),
  'err' : PurgeError,
});
export const Result_11 = IDL.Variant({
  'ok' : IDL.Vec(ActorRole),
  'err' : RegisterError,
});
export const Result_10 = IDL.Variant({
  'ok' : IDL.Vec(RefEntryView),
  'err' : ReferenceError,
});
export const Result_9 = IDL.Variant({
  'ok' : IDL.Vec(AnalysisDocumentView),
  'err' : ReferenceError,
});
export const RoleInfo = IDL.Record({ 'displayName' : IDL.Text, 'role' : Role });
export const MergeInput = IDL.Record({
  'destinationId' : LotId,
  'sourceId' : LotId,
  'payload' : IDL.Text,
});
export const AnalyticsBucket = IDL.Record({
  'key' : IDL.Text,
  'count' : IDL.Nat,
});
export const AnalyticsPoint = IDL.Record({
  'day' : IDL.Text,
  'lots' : IDL.Nat,
  'events' : IDL.Nat,
});
export const RegisterAnalytics = IDL.Record({
  'byKind' : IDL.Vec(AnalyticsBucket),
  'bySite' : IDL.Vec(AnalyticsBucket),
  'eventsOverTime' : IDL.Vec(AnalyticsPoint),
  'totalEvents' : IDL.Nat,
  'totalLots' : IDL.Nat,
  'lotsOverTime' : IDL.Vec(AnalyticsPoint),
  'byStatus' : IDL.Vec(AnalyticsBucket),
});
export const Result_8 = IDL.Variant({
  'ok' : RegisterAnalytics,
  'err' : ReferenceError,
});
export const Site = IDL.Variant({
  'KFB' : IDL.Null,
  'LUS' : IDL.Null,
  'MFB' : IDL.Null,
});
export const NewLotInput = IDL.Record({
  'gps' : IDL.Text,
  'grossG' : IDL.Text,
  'workingRef' : IDL.Text,
  'site' : Site,
  'sealNo' : IDL.Text,
  'fileHashes' : IDL.Vec(FileHash),
  'photoFileIds' : IDL.Vec(FileId),
  'licence' : IDL.Text,
  'lotType' : LotType,
  'project' : IDL.Text,
  'fileIds' : IDL.Vec(FileId),
});
export const CountBucket = IDL.Record({ 'key' : IDL.Text, 'count' : IDL.Nat });
export const ActivityPoint = IDL.Record({
  'day' : IDL.Text,
  'count' : IDL.Nat,
});
export const RegisterSummary = IDL.Record({
  'bySite' : IDL.Vec(CountBucket),
  'byType' : IDL.Vec(CountBucket),
  'totalEvents' : IDL.Nat,
  'totalLots' : IDL.Nat,
  'byStatus' : IDL.Vec(CountBucket),
  'activity' : IDL.Vec(ActivityPoint),
});
export const Result_5 = IDL.Variant({
  'ok' : IDL.Null,
  'err' : ReferenceError,
});
export const Result_6 = IDL.Variant({
  'ok' : IDL.Null,
  'err' : PermissionsError,
});
export const LotSearchHit = IDL.Record({
  'id' : LotId,
  'status' : LotStatus,
  'contentHash' : HashHex,
  'workingRef' : IDL.Text,
  'sealNo' : IDL.Text,
  'lotType' : LotType,
});
export const SetPrincipalOverrideInput = IDL.Record({
  'principal' : IDL.Principal,
  'capabilities' : IDL.Vec(Capability),
  'role' : Role,
});
export const Result_3 = IDL.Variant({
  'ok' : PrincipalOverride,
  'err' : PermissionsError,
});
export const SplitInput = IDL.Record({
  'children' : IDL.Vec(NewLotInput),
  'parentId' : LotId,
});
export const Result_2 = IDL.Variant({
  'ok' : IDL.Vec(LotView),
  'err' : RegisterError,
});
export const UpdateRefEntryInput = IDL.Record({
  'id' : IDL.Text,
  'active' : IDL.Bool,
  'displayName' : IDL.Text,
  'value' : IDL.Text,
  'sortOrder' : IDL.Nat,
});
export const UpdateRolePermissionsInput = IDL.Record({
  'capabilities' : IDL.Vec(Capability),
  'role' : Role,
});
export const Result = IDL.Variant({
  'ok' : RolePermissions,
  'err' : PermissionsError,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result_18], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addAnalysisDocument' : IDL.Func([NewAnalysisDocumentInput], [Result_17], []),
  'addReferenceEntry' : IDL.Func([NewRefEntryInput], [Result_1], []),
  'appendEvent' : IDL.Func([LotId, NewEventInput], [Result_7], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignRole' : IDL.Func([IDL.Principal, Role], [Result_16], []),
  'canonicalEventJson' : IDL.Func(
      [EventKind, IDL.Text, IDL.Vec(HashHex)],
      [IDL.Text],
      ['query'],
    ),
  'canonicalSnapshotJson' : IDL.Func([LotId], [IDL.Opt(IDL.Text)], ['query']),
  'changeStatus' : IDL.Func([LotId, StatusChangeInput], [Result_7], []),
  'claimAdmin' : IDL.Func([], [Result_15], []),
  'confirmPurge' : IDL.Func([], [Result_4], []),
  'deleteLot' : IDL.Func([LotId], [Result_14], []),
  'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
  'freezeLot' : IDL.Func([LotId], [Result_7], []),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLot' : IDL.Func([LotId], [IDL.Opt(LotView)], ['query']),
  'getMyCapabilities' : IDL.Func([], [IDL.Vec(Capability)], ['query']),
  'getMyRole' : IDL.Func([], [Role], ['query']),
  'getPermissions' : IDL.Func([], [Result_13], ['query']),
  'getPurgeRequest' : IDL.Func([], [Result_12], ['query']),
  'hasAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listActors' : IDL.Func([], [Result_11], ['query']),
  'listAllReferenceEntries' : IDL.Func([], [Result_10], ['query']),
  'listAnalysisDocuments' : IDL.Func([], [Result_9], ['query']),
  'listLots' : IDL.Func([], [IDL.Vec(LotView)], ['query']),
  'listReferenceEntries' : IDL.Func(
      [RefKind],
      [IDL.Vec(RefEntryView)],
      ['query'],
    ),
  'listRoles' : IDL.Func([], [IDL.Vec(RoleInfo)], ['query']),
  'mergeLots' : IDL.Func([MergeInput], [Result_7], []),
  'registerAnalytics' : IDL.Func([], [Result_8], ['query']),
  'registerLot' : IDL.Func([NewLotInput], [Result_7], []),
  'registerSummary' : IDL.Func([], [RegisterSummary], ['query']),
  'removeAnalysisDocument' : IDL.Func([IDL.Text], [Result_5], []),
  'removePrincipalOverride' : IDL.Func([IDL.Principal], [Result_6], []),
  'removeReferenceEntry' : IDL.Func([IDL.Text], [Result_5], []),
  'requestPurge' : IDL.Func([IDL.Text], [Result_4], []),
  'roleDisplayName' : IDL.Func([Role], [IDL.Text], ['query']),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'searchLots' : IDL.Func([IDL.Text], [IDL.Vec(LotSearchHit)], ['query']),
  'setPrincipalOverride' : IDL.Func(
      [SetPrincipalOverrideInput],
      [Result_3],
      [],
    ),
  'sha256Hex' : IDL.Func([IDL.Text], [HashHex], ['query']),
  'sha256HexOfBlob' : IDL.Func([IDL.Vec(IDL.Nat8)], [HashHex], ['query']),
  'splitLot' : IDL.Func([SplitInput], [Result_2], []),
  'statusHistory' : IDL.Func([LotId], [IDL.Vec(StatusChange)], ['query']),
  'suggestLotId' : IDL.Func([Site, IDL.Text], [LotId], ['query']),
  'updateReferenceEntry' : IDL.Func([UpdateRefEntryInput], [Result_1], []),
  'updateRolePermissions' : IDL.Func(
      [UpdateRolePermissionsInput],
      [Result],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result_18 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const HashHex = IDL.Text;
  const FileId = IDL.Text;
  const NewAnalysisDocumentInput = IDL.Record({
    'title' : IDL.Text,
    'contentHash' : HashHex,
    'note' : IDL.Text,
    'fileId' : FileId,
    'docKind' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const AnalysisDocumentView = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'contentHash' : HashHex,
    'note' : IDL.Text,
    'fileId' : FileId,
    'docKind' : IDL.Text,
    'uploadedAt' : Timestamp,
    'uploadedBy' : IDL.Principal,
  });
  const ReferenceError = IDL.Variant({
    'notAuthorized' : IDL.Null,
    'invalidInput' : IDL.Text,
    'duplicateEntry' : IDL.Text,
    'unknownDocument' : IDL.Text,
    'notAuthenticated' : IDL.Null,
    'unknownEntry' : IDL.Text,
  });
  const Result_17 = IDL.Variant({
    'ok' : AnalysisDocumentView,
    'err' : ReferenceError,
  });
  const RefKind = IDL.Variant({
    'status' : IDL.Null,
    'site' : IDL.Null,
    'form_default' : IDL.Null,
    'lot_kind' : IDL.Null,
    'caption' : IDL.Null,
    'event_kind' : IDL.Null,
  });
  const NewRefEntryInput = IDL.Record({
    'key' : IDL.Text,
    'displayName' : IDL.Text,
    'value' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'kind' : RefKind,
  });
  const RefEntryView = IDL.Record({
    'id' : IDL.Text,
    'key' : IDL.Text,
    'active' : IDL.Bool,
    'displayName' : IDL.Text,
    'value' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'kind' : RefKind,
  });
  const Result_1 = IDL.Variant({ 'ok' : RefEntryView, 'err' : ReferenceError });
  const LotId = IDL.Text;
  const EventKind = IDL.Variant({
    'cut' : IDL.Null,
    'merge' : IDL.Null,
    'retail' : IDL.Null,
    'moved' : IDL.Null,
    'assay' : IDL.Null,
    'note' : IDL.Null,
    'status_change' : IDL.Null,
    'sealed' : IDL.Null,
    'weighed' : IDL.Null,
    'correction' : IDL.Null,
    'split' : IDL.Null,
    'extracted' : IDL.Null,
    'photo' : IDL.Null,
  });
  const FileHash = IDL.Record({ 'contentHash' : HashHex, 'fileId' : FileId });
  const NewEventInput = IDL.Record({
    'kind' : EventKind,
    'fileHashes' : IDL.Vec(FileHash),
    'payload' : IDL.Text,
    'fileIds' : IDL.Vec(FileId),
  });
  const LotStatus = IDL.Variant({
    'closed' : IDL.Null,
    'assayed' : IDL.Null,
    'open' : IDL.Null,
    'in_transit' : IDL.Null,
    'retailed' : IDL.Null,
    'frozen' : IDL.Null,
  });
  const StatusChange = IDL.Record({
    'at' : Timestamp,
    'by' : IDL.Principal,
    'to' : LotStatus,
    'seq' : IDL.Nat,
    'from' : LotStatus,
  });
  const HashChainEntry = IDL.Record({
    'at' : Timestamp,
    'contentHash' : HashHex,
    'eventSeq' : IDL.Nat,
  });
  const EventView = IDL.Record({
    'at' : Timestamp,
    'by' : IDL.Principal,
    'seq' : IDL.Nat,
    'supersededBy' : IDL.Opt(IDL.Nat),
    'kind' : EventKind,
    'payloadHash' : HashHex,
    'payload' : IDL.Text,
    'fileIds' : IDL.Vec(FileId),
  });
  const LotType = IDL.Variant({ 'gold' : IDL.Null, 'emerald' : IDL.Null });
  const LotView = IDL.Record({
    'id' : LotId,
    'gps' : IDL.Text,
    'status' : LotStatus,
    'grossG' : IDL.Text,
    'contentHash' : HashHex,
    'workingRef' : IDL.Text,
    'statusHistory' : IDL.Vec(StatusChange),
    'sealNo' : IDL.Text,
    'hashChain' : IDL.Vec(HashChainEntry),
    'parentIds' : IDL.Vec(LotId),
    'events' : IDL.Vec(EventView),
    'fileHashes' : IDL.Vec(FileHash),
    'photoFileIds' : IDL.Vec(FileId),
    'frozen' : IDL.Bool,
    'licence' : IDL.Text,
    'lotType' : LotType,
    'project' : IDL.Text,
    'openedAt' : Timestamp,
    'openedBy' : IDL.Principal,
    'fileIds' : IDL.Vec(FileId),
  });
  const RegisterError = IDL.Variant({
    'duplicateLot' : LotId,
    'notAuthorized' : IDL.Null,
    'invalidInput' : IDL.Text,
    'unknownLot' : LotId,
    'lotFrozen' : LotId,
    'notAuthenticated' : IDL.Null,
  });
  const Result_7 = IDL.Variant({ 'ok' : LotView, 'err' : RegisterError });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Role = IDL.Variant({
    'workshop' : IDL.Null,
    'admin' : IDL.Null,
    'field_officer' : IDL.Null,
    'assayer' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ActorRole = IDL.Record({ 'principal' : IDL.Principal, 'role' : Role });
  const Result_16 = IDL.Variant({ 'ok' : ActorRole, 'err' : RegisterError });
  const StatusChangeInput = IDL.Record({
    'to' : LotStatus,
    'payload' : IDL.Text,
  });
  const Result_15 = IDL.Variant({ 'ok' : Role, 'err' : RegisterError });
  const PurgeRequestView = IDL.Record({
    'id' : IDL.Text,
    'confirmedBy' : IDL.Vec(IDL.Principal),
    'totalAdmins' : IDL.Nat,
    'confirmedCount' : IDL.Nat,
    'requiredConfirmations' : IDL.Nat,
    'requestedAt' : Timestamp,
    'requestedBy' : IDL.Principal,
  });
  const PurgeResult = IDL.Record({
    'purgedAt' : Timestamp,
    'purgedBy' : IDL.Principal,
    'eventsRemoved' : IDL.Nat,
    'lotsRemoved' : IDL.Nat,
    'filesRemoved' : IDL.Nat,
  });
  const PurgeOutcome = IDL.Variant({
    'pending' : PurgeRequestView,
    'executed' : PurgeResult,
  });
  const PurgeError = IDL.Variant({
    'alreadyConfirmed' : IDL.Null,
    'notAuthorized' : IDL.Null,
    'invalidInput' : IDL.Text,
    'alreadyRequested' : IDL.Null,
    'notAuthenticated' : IDL.Null,
    'noPendingRequest' : IDL.Null,
    'invalidPhrase' : IDL.Null,
  });
  const Result_4 = IDL.Variant({ 'ok' : PurgeOutcome, 'err' : PurgeError });
  const Result_14 = IDL.Variant({ 'ok' : LotId, 'err' : RegisterError });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result__1 = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const Capability = IDL.Variant({
    'change_status' : IDL.Null,
    'purge_register' : IDL.Null,
    'split_lot' : IDL.Null,
    'create_lot' : IDL.Null,
    'merge_lot' : IDL.Null,
    'manage_analysis_documents' : IDL.Null,
    'delete_lot' : IDL.Null,
    'freeze_lot' : IDL.Null,
    'manage_roles' : IDL.Null,
    'manage_reference_data' : IDL.Null,
    'append_event' : IDL.Null,
    'view_analytics' : IDL.Null,
  });
  const RolePermissions = IDL.Record({
    'capabilities' : IDL.Vec(Capability),
    'role' : Role,
  });
  const CapabilityRow = IDL.Record({
    'displayName' : IDL.Text,
    'roles' : IDL.Vec(Role),
    'capability' : Capability,
  });
  const PrincipalOverride = IDL.Record({
    'principal' : IDL.Principal,
    'capabilities' : IDL.Vec(Capability),
    'role' : Role,
  });
  const PermissionsView = IDL.Record({
    'roleDefaults' : IDL.Vec(RolePermissions),
    'capabilities' : IDL.Vec(CapabilityRow),
    'overrides' : IDL.Vec(PrincipalOverride),
  });
  const PermissionsError = IDL.Variant({
    'unknownPrincipal' : IDL.Principal,
    'notAuthorized' : IDL.Null,
    'invalidInput' : IDL.Text,
    'notAuthenticated' : IDL.Null,
  });
  const Result_13 = IDL.Variant({
    'ok' : PermissionsView,
    'err' : PermissionsError,
  });
  const Result_12 = IDL.Variant({
    'ok' : IDL.Opt(PurgeRequestView),
    'err' : PurgeError,
  });
  const Result_11 = IDL.Variant({
    'ok' : IDL.Vec(ActorRole),
    'err' : RegisterError,
  });
  const Result_10 = IDL.Variant({
    'ok' : IDL.Vec(RefEntryView),
    'err' : ReferenceError,
  });
  const Result_9 = IDL.Variant({
    'ok' : IDL.Vec(AnalysisDocumentView),
    'err' : ReferenceError,
  });
  const RoleInfo = IDL.Record({ 'displayName' : IDL.Text, 'role' : Role });
  const MergeInput = IDL.Record({
    'destinationId' : LotId,
    'sourceId' : LotId,
    'payload' : IDL.Text,
  });
  const AnalyticsBucket = IDL.Record({ 'key' : IDL.Text, 'count' : IDL.Nat });
  const AnalyticsPoint = IDL.Record({
    'day' : IDL.Text,
    'lots' : IDL.Nat,
    'events' : IDL.Nat,
  });
  const RegisterAnalytics = IDL.Record({
    'byKind' : IDL.Vec(AnalyticsBucket),
    'bySite' : IDL.Vec(AnalyticsBucket),
    'eventsOverTime' : IDL.Vec(AnalyticsPoint),
    'totalEvents' : IDL.Nat,
    'totalLots' : IDL.Nat,
    'lotsOverTime' : IDL.Vec(AnalyticsPoint),
    'byStatus' : IDL.Vec(AnalyticsBucket),
  });
  const Result_8 = IDL.Variant({
    'ok' : RegisterAnalytics,
    'err' : ReferenceError,
  });
  const Site = IDL.Variant({
    'KFB' : IDL.Null,
    'LUS' : IDL.Null,
    'MFB' : IDL.Null,
  });
  const NewLotInput = IDL.Record({
    'gps' : IDL.Text,
    'grossG' : IDL.Text,
    'workingRef' : IDL.Text,
    'site' : Site,
    'sealNo' : IDL.Text,
    'fileHashes' : IDL.Vec(FileHash),
    'photoFileIds' : IDL.Vec(FileId),
    'licence' : IDL.Text,
    'lotType' : LotType,
    'project' : IDL.Text,
    'fileIds' : IDL.Vec(FileId),
  });
  const CountBucket = IDL.Record({ 'key' : IDL.Text, 'count' : IDL.Nat });
  const ActivityPoint = IDL.Record({ 'day' : IDL.Text, 'count' : IDL.Nat });
  const RegisterSummary = IDL.Record({
    'bySite' : IDL.Vec(CountBucket),
    'byType' : IDL.Vec(CountBucket),
    'totalEvents' : IDL.Nat,
    'totalLots' : IDL.Nat,
    'byStatus' : IDL.Vec(CountBucket),
    'activity' : IDL.Vec(ActivityPoint),
  });
  const Result_5 = IDL.Variant({ 'ok' : IDL.Null, 'err' : ReferenceError });
  const Result_6 = IDL.Variant({ 'ok' : IDL.Null, 'err' : PermissionsError });
  const LotSearchHit = IDL.Record({
    'id' : LotId,
    'status' : LotStatus,
    'contentHash' : HashHex,
    'workingRef' : IDL.Text,
    'sealNo' : IDL.Text,
    'lotType' : LotType,
  });
  const SetPrincipalOverrideInput = IDL.Record({
    'principal' : IDL.Principal,
    'capabilities' : IDL.Vec(Capability),
    'role' : Role,
  });
  const Result_3 = IDL.Variant({
    'ok' : PrincipalOverride,
    'err' : PermissionsError,
  });
  const SplitInput = IDL.Record({
    'children' : IDL.Vec(NewLotInput),
    'parentId' : LotId,
  });
  const Result_2 = IDL.Variant({
    'ok' : IDL.Vec(LotView),
    'err' : RegisterError,
  });
  const UpdateRefEntryInput = IDL.Record({
    'id' : IDL.Text,
    'active' : IDL.Bool,
    'displayName' : IDL.Text,
    'value' : IDL.Text,
    'sortOrder' : IDL.Nat,
  });
  const UpdateRolePermissionsInput = IDL.Record({
    'capabilities' : IDL.Vec(Capability),
    'role' : Role,
  });
  const Result = IDL.Variant({
    'ok' : RolePermissions,
    'err' : PermissionsError,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result_18], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addAnalysisDocument' : IDL.Func(
        [NewAnalysisDocumentInput],
        [Result_17],
        [],
      ),
    'addReferenceEntry' : IDL.Func([NewRefEntryInput], [Result_1], []),
    'appendEvent' : IDL.Func([LotId, NewEventInput], [Result_7], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignRole' : IDL.Func([IDL.Principal, Role], [Result_16], []),
    'canonicalEventJson' : IDL.Func(
        [EventKind, IDL.Text, IDL.Vec(HashHex)],
        [IDL.Text],
        ['query'],
      ),
    'canonicalSnapshotJson' : IDL.Func([LotId], [IDL.Opt(IDL.Text)], ['query']),
    'changeStatus' : IDL.Func([LotId, StatusChangeInput], [Result_7], []),
    'claimAdmin' : IDL.Func([], [Result_15], []),
    'confirmPurge' : IDL.Func([], [Result_4], []),
    'deleteLot' : IDL.Func([LotId], [Result_14], []),
    'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
    'freezeLot' : IDL.Func([LotId], [Result_7], []),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLot' : IDL.Func([LotId], [IDL.Opt(LotView)], ['query']),
    'getMyCapabilities' : IDL.Func([], [IDL.Vec(Capability)], ['query']),
    'getMyRole' : IDL.Func([], [Role], ['query']),
    'getPermissions' : IDL.Func([], [Result_13], ['query']),
    'getPurgeRequest' : IDL.Func([], [Result_12], ['query']),
    'hasAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listActors' : IDL.Func([], [Result_11], ['query']),
    'listAllReferenceEntries' : IDL.Func([], [Result_10], ['query']),
    'listAnalysisDocuments' : IDL.Func([], [Result_9], ['query']),
    'listLots' : IDL.Func([], [IDL.Vec(LotView)], ['query']),
    'listReferenceEntries' : IDL.Func(
        [RefKind],
        [IDL.Vec(RefEntryView)],
        ['query'],
      ),
    'listRoles' : IDL.Func([], [IDL.Vec(RoleInfo)], ['query']),
    'mergeLots' : IDL.Func([MergeInput], [Result_7], []),
    'registerAnalytics' : IDL.Func([], [Result_8], ['query']),
    'registerLot' : IDL.Func([NewLotInput], [Result_7], []),
    'registerSummary' : IDL.Func([], [RegisterSummary], ['query']),
    'removeAnalysisDocument' : IDL.Func([IDL.Text], [Result_5], []),
    'removePrincipalOverride' : IDL.Func([IDL.Principal], [Result_6], []),
    'removeReferenceEntry' : IDL.Func([IDL.Text], [Result_5], []),
    'requestPurge' : IDL.Func([IDL.Text], [Result_4], []),
    'roleDisplayName' : IDL.Func([Role], [IDL.Text], ['query']),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'searchLots' : IDL.Func([IDL.Text], [IDL.Vec(LotSearchHit)], ['query']),
    'setPrincipalOverride' : IDL.Func(
        [SetPrincipalOverrideInput],
        [Result_3],
        [],
      ),
    'sha256Hex' : IDL.Func([IDL.Text], [HashHex], ['query']),
    'sha256HexOfBlob' : IDL.Func([IDL.Vec(IDL.Nat8)], [HashHex], ['query']),
    'splitLot' : IDL.Func([SplitInput], [Result_2], []),
    'statusHistory' : IDL.Func([LotId], [IDL.Vec(StatusChange)], ['query']),
    'suggestLotId' : IDL.Func([Site, IDL.Text], [LotId], ['query']),
    'updateReferenceEntry' : IDL.Func([UpdateRefEntryInput], [Result_1], []),
    'updateRolePermissions' : IDL.Func(
        [UpdateRolePermissionsInput],
        [Result],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };