/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityPoint { 'day' : string, 'count' : bigint }
export interface ActorRole { 'principal' : Principal, 'role' : Role }
export interface AnalysisDocumentView {
  'id' : string,
  'title' : string,
  'contentHash' : HashHex,
  'note' : string,
  'fileId' : FileId,
  'docKind' : string,
  'uploadedAt' : Timestamp,
  'uploadedBy' : Principal,
}
export interface AnalyticsBucket { 'key' : string, 'count' : bigint }
export interface AnalyticsPoint {
  'day' : string,
  'lots' : bigint,
  'events' : bigint,
}
export type Capability = { 'change_status' : null } |
  { 'purge_register' : null } |
  { 'split_lot' : null } |
  { 'create_lot' : null } |
  { 'merge_lot' : null } |
  { 'manage_analysis_documents' : null } |
  { 'delete_lot' : null } |
  { 'freeze_lot' : null } |
  { 'manage_roles' : null } |
  { 'manage_reference_data' : null } |
  { 'append_event' : null } |
  { 'view_analytics' : null };
export interface CapabilityRow {
  'displayName' : string,
  'roles' : Array<Role>,
  'capability' : Capability,
}
export interface Cell { 'value' : Value, 'name' : string }
export interface CountBucket { 'key' : string, 'count' : bigint }
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type EventKind = { 'cut' : null } |
  { 'merge' : null } |
  { 'retail' : null } |
  { 'moved' : null } |
  { 'assay' : null } |
  { 'note' : null } |
  { 'status_change' : null } |
  { 'sealed' : null } |
  { 'weighed' : null } |
  { 'correction' : null } |
  { 'split' : null } |
  { 'extracted' : null } |
  { 'photo' : null };
export interface EventView {
  'at' : Timestamp,
  'by' : Principal,
  'seq' : bigint,
  'supersededBy' : [] | [bigint],
  'kind' : EventKind,
  'payloadHash' : HashHex,
  'payload' : string,
  'fileIds' : Array<FileId>,
}
export interface FileHash { 'contentHash' : HashHex, 'fileId' : FileId }
export type FileId = string;
export interface HashChainEntry {
  'at' : Timestamp,
  'contentHash' : HashHex,
  'eventSeq' : bigint,
}
export type HashHex = string;
export type LotId = string;
export interface LotSearchHit {
  'id' : LotId,
  'status' : LotStatus,
  'contentHash' : HashHex,
  'workingRef' : string,
  'sealNo' : string,
  'lotType' : LotType,
}
export type LotStatus = { 'closed' : null } |
  { 'assayed' : null } |
  { 'open' : null } |
  { 'in_transit' : null } |
  { 'retailed' : null } |
  { 'frozen' : null };
export type LotType = { 'gold' : null } |
  { 'emerald' : null };
export interface LotView {
  'id' : LotId,
  'gps' : string,
  'status' : LotStatus,
  'grossG' : string,
  'contentHash' : HashHex,
  'workingRef' : string,
  'statusHistory' : Array<StatusChange>,
  'sealNo' : string,
  'hashChain' : Array<HashChainEntry>,
  'parentIds' : Array<LotId>,
  'events' : Array<EventView>,
  'fileHashes' : Array<FileHash>,
  'photoFileIds' : Array<FileId>,
  'frozen' : boolean,
  'licence' : string,
  'lotType' : LotType,
  'project' : string,
  'openedAt' : Timestamp,
  'openedBy' : Principal,
  'fileIds' : Array<FileId>,
}
export interface MergeInput {
  'destinationId' : LotId,
  'sourceId' : LotId,
  'payload' : string,
}
export interface NewAnalysisDocumentInput {
  'title' : string,
  'contentHash' : HashHex,
  'note' : string,
  'fileId' : FileId,
  'docKind' : string,
}
export interface NewEventInput {
  'kind' : EventKind,
  'fileHashes' : Array<FileHash>,
  'payload' : string,
  'fileIds' : Array<FileId>,
}
export interface NewLotInput {
  'gps' : string,
  'grossG' : string,
  'workingRef' : string,
  'site' : Site,
  'sealNo' : string,
  'fileHashes' : Array<FileHash>,
  'photoFileIds' : Array<FileId>,
  'licence' : string,
  'lotType' : LotType,
  'project' : string,
  'fileIds' : Array<FileId>,
}
export interface NewRefEntryInput {
  'key' : string,
  'displayName' : string,
  'value' : string,
  'sortOrder' : bigint,
  'kind' : RefKind,
}
export type PermissionsError = { 'unknownPrincipal' : Principal } |
  { 'notAuthorized' : null } |
  { 'invalidInput' : string } |
  { 'notAuthenticated' : null };
export interface PermissionsView {
  'roleDefaults' : Array<RolePermissions>,
  'capabilities' : Array<CapabilityRow>,
  'overrides' : Array<PrincipalOverride>,
}
export interface PrincipalOverride {
  'principal' : Principal,
  'capabilities' : Array<Capability>,
  'role' : Role,
}
export type PurgeError = { 'alreadyConfirmed' : null } |
  { 'notAuthorized' : null } |
  { 'invalidInput' : string } |
  { 'alreadyRequested' : null } |
  { 'notAuthenticated' : null } |
  { 'noPendingRequest' : null } |
  { 'invalidPhrase' : null };
export type PurgeOutcome = { 'pending' : PurgeRequestView } |
  { 'executed' : PurgeResult };
export interface PurgeRequestView {
  'id' : string,
  'confirmedBy' : Array<Principal>,
  'totalAdmins' : bigint,
  'confirmedCount' : bigint,
  'requiredConfirmations' : bigint,
  'requestedAt' : Timestamp,
  'requestedBy' : Principal,
}
export interface PurgeResult {
  'purgedAt' : Timestamp,
  'purgedBy' : Principal,
  'eventsRemoved' : bigint,
  'lotsRemoved' : bigint,
  'filesRemoved' : bigint,
}
export interface RefEntryView {
  'id' : string,
  'key' : string,
  'active' : boolean,
  'displayName' : string,
  'value' : string,
  'sortOrder' : bigint,
  'kind' : RefKind,
}
export type RefKind = { 'status' : null } |
  { 'site' : null } |
  { 'form_default' : null } |
  { 'lot_kind' : null } |
  { 'caption' : null } |
  { 'event_kind' : null };
export type ReferenceError = { 'notAuthorized' : null } |
  { 'invalidInput' : string } |
  { 'duplicateEntry' : string } |
  { 'unknownDocument' : string } |
  { 'notAuthenticated' : null } |
  { 'unknownEntry' : string };
export interface RegisterAnalytics {
  'byKind' : Array<AnalyticsBucket>,
  'bySite' : Array<AnalyticsBucket>,
  'eventsOverTime' : Array<AnalyticsPoint>,
  'totalEvents' : bigint,
  'totalLots' : bigint,
  'lotsOverTime' : Array<AnalyticsPoint>,
  'byStatus' : Array<AnalyticsBucket>,
}
export type RegisterError = { 'duplicateLot' : LotId } |
  { 'notAuthorized' : null } |
  { 'invalidInput' : string } |
  { 'unknownLot' : LotId } |
  { 'lotFrozen' : LotId } |
  { 'notAuthenticated' : null };
export interface RegisterSummary {
  'bySite' : Array<CountBucket>,
  'byType' : Array<CountBucket>,
  'totalEvents' : bigint,
  'totalLots' : bigint,
  'byStatus' : Array<CountBucket>,
  'activity' : Array<ActivityPoint>,
}
export type Result = { 'ok' : RolePermissions } |
  { 'err' : PermissionsError };
export type Result_1 = { 'ok' : RefEntryView } |
  { 'err' : ReferenceError };
export type Result_10 = { 'ok' : Array<RefEntryView> } |
  { 'err' : ReferenceError };
export type Result_11 = { 'ok' : Array<ActorRole> } |
  { 'err' : RegisterError };
export type Result_12 = { 'ok' : [] | [PurgeRequestView] } |
  { 'err' : PurgeError };
export type Result_13 = { 'ok' : PermissionsView } |
  { 'err' : PermissionsError };
export type Result_14 = { 'ok' : LotId } |
  { 'err' : RegisterError };
export type Result_15 = { 'ok' : Role } |
  { 'err' : RegisterError };
export type Result_16 = { 'ok' : ActorRole } |
  { 'err' : RegisterError };
export type Result_17 = { 'ok' : AnalysisDocumentView } |
  { 'err' : ReferenceError };
export type Result_18 = { 'ok' : null } |
  { 'err' : Error };
export type Result_2 = { 'ok' : Array<LotView> } |
  { 'err' : RegisterError };
export type Result_3 = { 'ok' : PrincipalOverride } |
  { 'err' : PermissionsError };
export type Result_4 = { 'ok' : PurgeOutcome } |
  { 'err' : PurgeError };
export type Result_5 = { 'ok' : null } |
  { 'err' : ReferenceError };
export type Result_6 = { 'ok' : null } |
  { 'err' : PermissionsError };
export type Result_7 = { 'ok' : LotView } |
  { 'err' : RegisterError };
export type Result_8 = { 'ok' : RegisterAnalytics } |
  { 'err' : ReferenceError };
export type Result_9 = { 'ok' : Array<AnalysisDocumentView> } |
  { 'err' : ReferenceError };
export interface Result__1 { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Role = { 'workshop' : null } |
  { 'admin' : null } |
  { 'field_officer' : null } |
  { 'assayer' : null } |
  { 'guest' : null };
export interface RoleInfo { 'displayName' : string, 'role' : Role }
export interface RolePermissions {
  'capabilities' : Array<Capability>,
  'role' : Role,
}
export interface SetPrincipalOverrideInput {
  'principal' : Principal,
  'capabilities' : Array<Capability>,
  'role' : Role,
}
export type Site = { 'KFB' : null } |
  { 'LUS' : null } |
  { 'MFB' : null };
export interface SplitInput {
  'children' : Array<NewLotInput>,
  'parentId' : LotId,
}
export interface StatusChange {
  'at' : Timestamp,
  'by' : Principal,
  'to' : LotStatus,
  'seq' : bigint,
  'from' : LotStatus,
}
export interface StatusChangeInput { 'to' : LotStatus, 'payload' : string }
export type Timestamp = bigint;
export interface UpdateRefEntryInput {
  'id' : string,
  'active' : boolean,
  'displayName' : string,
  'value' : string,
  'sortOrder' : bigint,
}
export interface UpdateRolePermissionsInput {
  'capabilities' : Array<Capability>,
  'role' : Role,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
/**
 * / JOA Gold Book — composition root for the provenance register backend.
 * / State is declared here with types only; initial values come from the
 * / migration chain in migrations/.
 * /
 * / Each piece of state has exactly one home: the register's lots, file hashes
 * / and OQL lot index live inside `registerState`, the role map lives inside
 * / `rolesState`, the admin-managed reference data, analysis documents and
 * / their counters live inside `referenceState`, the pending purge request
 * / lives inside `purgeState`, and the role permission defaults and
 * / per-principal overrides live inside `permissionsState`. The migration's
 * / `NewActor` matches this actor shape exactly.
 */
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result_18>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  /**
   * / Store an analysis document. Admin only.
   */
  'addAnalysisDocument' : ActorMethod<[NewAnalysisDocumentInput], Result_17>,
  /**
   * / Add a reference entry. Admin only.
   */
  'addReferenceEntry' : ActorMethod<[NewRefEntryInput], Result_1>,
  /**
   * / Append a provenance event to a lot. The caller's role must permit the
   * / event kind.
   */
  'appendEvent' : ActorMethod<[LotId, NewEventInput], Result_7>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Assign a role to a principal. Admin only.
   */
  'assignRole' : ActorMethod<[Principal, Role], Result_16>,
  /**
   * / Canonical event payload JSON, so the frontend can recompute payloadHash.
   */
  'canonicalEventJson' : ActorMethod<
    [EventKind, string, Array<HashHex>],
    string
  >,
  /**
   * / Canonical lot snapshot JSON, so the frontend can recompute contentHash.
   * / Built through the register's own snapshot path, so it reproduces the
   * / sealed contentHash exactly, including event file content hashes and every
   * / event's payloadHash.
   */
  'canonicalSnapshotJson' : ActorMethod<[LotId], [] | [string]>,
  /**
   * / Record a status change as a new provenance event in the lot's chain. The
   * / caller's role must be permitted to make the transition.
   */
  'changeStatus' : ActorMethod<[LotId, StatusChangeInput], Result_7>,
  /**
   * / The first identity that claims admin becomes admin.
   */
  'claimAdmin' : ActorMethod<[], Result_15>,
  /**
   * / Confirm the open purge request. Admin only. Executes automatically once
   * / more than half of the currently-assigned admins have confirmed.
   */
  'confirmPurge' : ActorMethod<[], Result_4>,
  /**
   * / Delete exactly one block, removing its events, hash chain and stored file
   * / references. Requires the `#delete_lot` capability, held by admin by
   * / default; a caller without it is refused with `#notAuthorized`. This is the
   * / register's one explicit destructive action.
   */
  'deleteLot' : ActorMethod<[LotId], Result_14>,
  'execute' : ActorMethod<[string], Result__1>,
  /**
   * / Freeze a lot. Admin only.
   */
  'freezeLot' : ActorMethod<[LotId], Result_7>,
  /**
   * / The backend's public API documentation as Markdown.
   */
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Fetch a single lot by id. Public read.
   */
  'getLot' : ActorMethod<[LotId], [] | [LotView]>,
  /**
   * / The calling principal's effective capabilities.
   */
  'getMyCapabilities' : ActorMethod<[], Array<Capability>>,
  /**
   * / The role of the calling principal.
   */
  'getMyRole' : ActorMethod<[], Role>,
  /**
   * / The full Permissions section. Admin only.
   */
  'getPermissions' : ActorMethod<[], Result_13>,
  /**
   * / The open purge request and its confirmation progress, if any. Admin only.
   */
  'getPurgeRequest' : ActorMethod<[], Result_12>,
  /**
   * / Whether an administrator already exists. Public and non-sensitive: it
   * / lets the frontend hide the claim action once the role has been claimed.
   */
  'hasAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / List every actor with its principal and role. Admin only.
   */
  'listActors' : ActorMethod<[], Result_11>,
  /**
   * / List every reference entry, including inactive ones. Admin only.
   */
  'listAllReferenceEntries' : ActorMethod<[], Result_10>,
  /**
   * / List the stored analysis documents, newest first. Admin only.
   */
  'listAnalysisDocuments' : ActorMethod<[], Result_9>,
  /**
   * / List every lot in the register. Public read.
   */
  'listLots' : ActorMethod<[], Array<LotView>>,
  /**
   * / List the active reference entries of one kind. Public read: the register's
   * / forms and displays are driven by this data.
   */
  'listReferenceEntries' : ActorMethod<[RefKind], Array<RefEntryView>>,
  /**
   * / Every role with its display name, for the admin panel.
   */
  'listRoles' : ActorMethod<[], Array<RoleInfo>>,
  /**
   * / Merge a source lot into a destination lot. Workshop or admin only.
   */
  'mergeLots' : ActorMethod<[MergeInput], Result_7>,
  /**
   * / The register's own live analytics. Admin only.
   */
  'registerAnalytics' : ActorMethod<[], Result_8>,
  /**
   * / Register a new lot. Signed-in callers with a role that permits the lot
   * / type only.
   */
  'registerLot' : ActorMethod<[NewLotInput], Result_7>,
  /**
   * / Aggregate register data for the home-page graph. Public read.
   */
  'registerSummary' : ActorMethod<[], RegisterSummary>,
  /**
   * / Remove an analysis document. Admin only.
   */
  'removeAnalysisDocument' : ActorMethod<[string], Result_5>,
  /**
   * / Remove a per-principal permission override. Admin only.
   */
  'removePrincipalOverride' : ActorMethod<[Principal], Result_6>,
  /**
   * / Remove a reference entry. Admin only.
   */
  'removeReferenceEntry' : ActorMethod<[string], Result_5>,
  /**
   * / Open a purge request. Admin only. The phrase must be typed verbatim.
   */
  'requestPurge' : ActorMethod<[string], Result_4>,
  /**
   * / The human-readable display name for a role. 'Assayer' reads
   * / 'Quality Tester' and 'Workshop' reads 'Custom Role'.
   */
  'roleDisplayName' : ActorMethod<[Role], string>,
  'schema' : ActorMethod<[], string>,
  /**
   * / Search across lot id, content-hash prefix, seal number and working ref.
   */
  'searchLots' : ActorMethod<[string], Array<LotSearchHit>>,
  /**
   * / Set a per-principal permission override for a role. Admin only.
   */
  'setPrincipalOverride' : ActorMethod<[SetPrincipalOverrideInput], Result_3>,
  /**
   * / SHA-256 of a UTF-8 text as 64 lowercase hex characters.
   */
  'sha256Hex' : ActorMethod<[string], HashHex>,
  /**
   * / SHA-256 of raw file bytes as 64 lowercase hex characters.
   */
  'sha256HexOfBlob' : ActorMethod<[Uint8Array], HashHex>,
  /**
   * / Split a lot into child lots. Workshop or admin only.
   */
  'splitLot' : ActorMethod<[SplitInput], Result_2>,
  /**
   * / The status-change history for a lot, in provenance order. Public read.
   */
  'statusHistory' : ActorMethod<[LotId], Array<StatusChange>>,
  /**
   * / Suggest the next lot id for a site and date.
   */
  'suggestLotId' : ActorMethod<[Site, string], LotId>,
  /**
   * / Edit a reference entry. Admin only.
   */
  'updateReferenceEntry' : ActorMethod<[UpdateRefEntryInput], Result_1>,
  /**
   * / Edit a role's default permission set. Admin only.
   */
  'updateRolePermissions' : ActorMethod<[UpdateRolePermissionsInput], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];